### ISSUE TITLE
Board 10.5 is not transmiting

### ISSUE THREAD

**Issue by kagouraki** [peterantypas/maiana#107]
Hello Peter, 

I bought a kit board 10.5 with nmea183 breackout board last summer but i havent used it yet. Now i am trying to make it work. I assembled everything and i am recieving AIS signals and gps is all working. My problem is with the transmission. I programmed my Station data. The string i sended is this one : station 239108400,AIDA,SY7899,36,12,4,0,0
It is programmed probably because i see the TX led blinking once in a while. 
Is there a command to send to test the transmission? I have a chinese clone spectrum analyzer but i cant take it with me and im my garage i dont get gps signal for the board to transmit. I dont have another AIS reciever to check. I see in marine traffic. I had it on on a trip with marine trafic coverage for two hours but i was not on marinetraffic.

How should i procceed ? 

Thank you !

**Comment by peterantypas** [comment]
If you see $PAITX sentences in the NMEA output and the TX LED blinks momentarily, then it's transmitting. Another AIS receiver is really the only reliable way to verify though. MarineTraffic isn't 100% reliable from experience.

**Comment by peterantypas** [comment]
I'm not sure how old the FW is on your board, but there should be a "tx test" command which will generate a 1-second randomly modulated signal on a random channel. You can use a spectrum analyzer to capture it, but you'd better make sure you have a lot of attenuation as you could easily fry its front end with +33dBm. Even my HP8563 doesn't tolerate this input level.

**Comment by kagouraki** [comment]
Ok i will try with montesier hat and report back. I see the $PAITX sentence and led blinks. Give me an hour i will test it now. Thank you for your immediatly response.

**Comment by kagouraki** [comment]
Sorry took longer than i was hoping. 
You can close this Issue. The unit is transmitting. Marinetraffic SUCKS.
By the way. The icon was yellow on opencpn and never turned green.Also the name was not displayed. The units where 3 meters apart. Is this normal ? 
Also the flag was Great Britain. How do i change it to Greece?

**Comment by peterantypas** [comment]
The static reports are transmitted every 5 minutes. Did you wait long enough?

**Comment by kagouraki** [comment]
Yes. I was about 20 minutes there. Is there a way to change the flag ?

**Comment by peterantypas** [comment]
There is nothing on the AIS side that controls "the flag". That's OpenCPN
interpretation of MMSI

**Comment by kagouraki** [comment]
Perfect. I had a random number. Thank you peter ! Goodnight. Or day in America 😅
