### ISSUE TITLE
Build it from modules

### ISSUE THREAD

**Issue by muebau** [peterantypas/maiana#58]
Hi,
when I saw this project for the first time I ordered some modules to build a simple AIS from modules. The parts arrived mid 2020 but the project made a lot of progress and changed a lot. As the project is a little bit on hold I wondered if I could use the current source code and build a poor mans versions.
It would be bulky but would give me a simple AIS receiver. The transmission power I to low but might be better than no transmission at all.

What do you think? 

The modules:

GN-801 GPS
https://www.aliexpress.com/item/32951163811.html

SX1278 170mhz 1W
https://www.aliexpress.com/item/33044516902.html

SI4463 170Mhz 500mW
https://www.aliexpress.com/item/32802449702.html

Stm32f302cbt6
https://www.aliexpress.com/item/4000906426082.html

SMA cable Y pigtail RG316
https://www.aliexpress.com/item/1005001693573105.html

**Comment by JohnDevine** [comment]
I am very interested too. Any way I can help? I build quite a lot of IOT gear and code in C++ and node red. I have a 3d printer as well. We also have a yacht that the lightning has trashed our AIS transponder ... so I have motivation :)
