### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by david-522** [peterantypas/maiana#62]
Very nice Job. I am trying to build the project(firmware folder) in eclipse mars.2 DS-5 Professional Edition
Version: 5.26.2.  I just downloaded the eclipse  and it dose not show any toolchain in tool chain editor to select.  I keep getting this error: make: *** No rule to make target 'all'.  Stop.
I tryed to add ARM plug in but I could not do it.
How could I compile and build the project for Arm processor. 

Thanks.

**Comment by peterantypas** [comment]
Why such an old version of Eclipse? I would start here:

[https://www.eclipse.org/cdt/downloads.php](https://www.eclipse.org/cdt/downloads.php
)

**Comment by peterantypas** [comment]
Also, after you install Eclipse CDT (not the Java one), you must still install this package:

![Screenshot from 2021-05-18 07-29-18](https://user-images.githubusercontent.com/1565933/118669788-e63cce00-b7aa-11eb-880c-11bfc6d54e98.png)

**Comment by david-522** [comment]
Thank you very much Peter. That was very helpful. the project is build completely now. I am not able to Generate Hex file .  is it necessary to have hex file or just elf format will be fine.

Regards,
David.

**Comment by peterantypas** [comment]
This is often an issue with plain Eclipse. I find that I need to add those rules explicitly.

First, configure the build page for outputting a raw binary (not hex). Then do this:

![Uploading Screenshot from 2021-05-21 15-37-35.png…]()

**Comment by david-522** [comment]
Thanks Peter. I really love this job you did.I am using STM412 and  I build the project with eclipse and also uses J-Flash software to load the elf file into the micro. I send Cli command  but I dont get any reaction. if it is possible for you Please give me your email then I will send you the elf file that I make. I will appreciate if you take a look at it.

**Comment by peterantypas** [comment]
I've seen this on occasion too, what happens when you powercycle/reset and try again? Also, can you confirm the UART signal is getting through? The test pads for the UART are here:

![Screenshot from 2021-05-22 07-44-00](https://user-images.githubusercontent.com/1565933/119230555-89565600-bad1-11eb-8b9f-724ab335e5b2.png)

**Comment by david-522** [comment]
Thanks for the Advice. I have checked the UART and it is working OK. I wrote a code in keil and looped the send and receive pins.
When I rest the board I dont see any reaction. cli command do nothing So I guess the elf file that I made is not OK. Is it possible for you to send me your elf file so I could check it on my board. I am very interested to so how it works. 
d.zeinali.n@gmail.com

Thanks,
Regards.

**Comment by peterantypas** [comment]
Is your terminal sending CRLF at end of line?

**Comment by peterantypas** [comment]
@david-522 did you ever resolve this?

**Comment by david-522** [comment]
Thanks for asking. Nothing actually. could not get any reply.

**Comment by peterantypas** [comment]
What board revision did you use? I can try sending you a binary to flash into it directly.

**Comment by david-522** [comment]
it is 10.0

**Comment by peterantypas** [comment]
Try this (gunzip first)
[maiana-transponder.bin.gz](https://github.com/peterantypas/maiana/files/7245425/maiana-transponder.bin.gz)

**Comment by peterantypas** [comment]
Also, you may want to replace R1 and R2 with 0 ohm bridges and lose the Zeners next to them just in case they're interfering ...
