### ISSUE TITLE
TX switch may prevent transponder from booting

### ISSUE THREAD

**Issue by peterantypas** [peterantypas/maiana#72]
The current design (including board revs shipped in the kit) directs the "TX_OFF" signal to the GPIO PA12. This was an unfortunate choice, as it turns out, because this pin is USB D+ and the effect of the "TX off" setting is for it to be pulled down to GND hard via a buffer MOSFET.

This causes some boards to hang and draw a significant amount of current during POR. But not every board does this.

The best workaround is to always keep the breakout switch to "TX on" position during power-up.

**Comment by gah67** [comment]
I was just looking at the NMEA0183 breakout schematic to see if a capacitor could be added to make an RC circuit to delay the +5V signal and I have a query - isn't the 'TX_DISABLE/3.1B' on the 'wrong' side of R9? Where is is is not current limited is it??

**Comment by peterantypas** [comment]
R9 was there to prevent a floating signal during post-SMT testing (prior to soldering the switches). But the circuit has to change now to introduce an RC delay. Even a very short (200ms) delay seems to work when I test this manually.

**Comment by peterantypas** [comment]
So the short-term solution is I redesign both the USB and NME0183 breakouts. I will email the folks who bought kits (there's quite a few already) and explain.

**Comment by peterantypas** [comment]
The NMEA2000 breakout contains a GreenPAK. It's trivial to add a delay for TX control in there.

**Comment by peterantypas** [comment]
I can validate this by reworking a USB breakout board. I will cut this trace on the bottom and scrape solder mask to make an RC delay.

![Screenshot from 2021-07-14 08-36-36](https://user-images.githubusercontent.com/1565933/125650364-57cc9b71-a365-41fe-b3d8-a25ec56d657f.png)

**Comment by gah67** [comment]
That's a very handy via!

**Comment by peterantypas** [comment]
I have confirmed that all STM32L4x series MCUs drive PA12 high during reset, and shorting it to GND causes all kinds of problems. Time delay is one possible fix, but a better fix is to introduce the right pull-down resistor value to limit that inrush current during bootup. Long term fix is to redesign the transponder board.

**Comment by peterantypas** [comment]
Turns out that this is more of a POR glitch:

![SDS00012](https://user-images.githubusercontent.com/1565933/126072614-b8b545dc-4316-4325-b559-dabe8d40e941.png)

Yellow is NRST, purple is PA11, blue is PA12, green is BOOT0.

**Comment by peterantypas** [comment]
PA12 wants to rise above 2V during power-up. But this condition expires withing 400us so a delay will take care of it.

**Comment by peterantypas** [comment]
Alright, 10K + 1uF RC delay took care of this. All breakout boards have been redesigned and are in fab.
