### ISSUE TITLE
MAIANA needs its own bootloader

### ISSUE THREAD

**Issue by peterantypas** [peterantypas/maiana#89]
The ROM bootloader built into the STM32 MCU has no means of verifying the integrity of application firmware. It simply jumps to 0x08000000 (flash base) if the first 8 bytes contain a valid stack pointer and program counter. So if a previous firmware update failed mid-flight, but the first flash page looks valid, then the MCU will start executing a corrupt application. This will almost certainly brick it.

This presents a real risk for a device like MAIANA which is out-of-reach. If this were to happen, the only way to rescue the unit would be to disassemble it and attach an SWD programmer.

The solution to this is to introduce a *minimal* bootloader which only performs firmware integrity checking. This program will occupy the first page of flash at 0x08000000, so it will be the first block to be erased and flashed during an update. The  page will also contain the metadata for the actual firmware image (address, size, checksum) so it will be completely self-contained.

During reset, this bootloader will check for the presence of a valid application firmware image. If the image passes the integrity check, then it will jump to it. If not, then it will jump to the ROM bootloader for another firmware update. This way, if a previous firmware update failed halfway through, the next reset will always enter firmware update mode rather than execute a corrupt application.

**Comment by muebau** [comment]
Will this minimal bootloader be written once and most likely newer written again or will it be written every time a new MAIANA firmware update is done?

If there would be a way to only write the memory pages of MAIANA the bootloader has now risk of being corrupted in other case the critical memory of 0x08000000 could become corrupted even if very unlikely because of the small size, simple functionality, etc. .

**Comment by peterantypas** [comment]
That's entirely up to us to define. The ROM bootloader can erase and write any address in flash, so we can arbitrarily push application firmware to 0x08000800 or even higher. Additionally, we can also write protect page 0 via option bytes. So we can actually have a one-time write of that page with this basic bootloader, but then we can never change it again either.

**Comment by muebau** [comment]
Some systems employ a A/B partition scheme to make sure there is no way to flash anything without a way back to some working code. I can't think of a trick to do that in MAIANA except with some watchdog or physical switch to choose the "other" bootloader.
Anyway this way it would be save to flash bootloader B from bootloader A and reboot into bootloader B. If some sort of verification (watchdog, signature, etc.) fails the next boot would go again with bootloader A else A could be flash as a next step. I think its clear.

The other thing could be a switch to decide which bootloader will be used. I think there is no 'free' switch for the boot process, is it?

**Comment by peterantypas** [comment]
The STM32 platform doesn't support such a scheme, as there is no hardware "switch" to force booting from an address other than 0x08000000. A software bootloader at that page is the only way to do this. 

That, you can't just deploy a firmware binary at any arbitrary address in flash; it has to be _linked_ for that address. And that makes an A/B scheme impossible.

**Comment by peterantypas** [comment]
I think the immutable bootloader at flash page 0 is the best option. The question now is how and where do we write firmware metadata (address, size, checksum) for the bootloader to pick up and verify. It has to be in flash, as the bootloader will not have any peripherals such i2c initialized (code won't fit otherwise). 

I'm leaning toward dedicating flash page 1 (0x08000800) to that metadata and linking binaries to start at page 2 (0x08001000). Under this scheme, page 1 would be erased first and written last, only after the entire new binary has been flashed. Any corruption of that page will just trigger firmware update again.

I'm open to other ideas as well.

**Comment by peterantypas** [comment]
There is another way to achieve the desired effect: Redesign the hardware to allow the user to force firmware update upon power-up. This can be achieved by manipulating the BOOT0 pin which is currently just a test pad for the jig and it's not exposed outside the main board (there are no more signals left on the Cat5 to wire it either).

This could be done by adding a GreenPAK to the board which monitors the TX switch and counts the number of edges in a given time period. To force a FW update, the user would need to cycle the TX switch on/off very quickly a few times, then the GreenPAK would force a boot into DFU mode in the same way it's done inside the NMEA2000 adapter right now.

Under this scheme, there would be no need for any bootloader and firmware would remain as is.

**Comment by peterantypas** [comment]
A simpler way to achieve "atomicity" in firmware update is to erase page 0 immediately and write it last. If something breaks in the interim, the system has no firmware as far are the ROM bootloader is concerned, so it will enter DFU mode upon reset.

**Comment by peterantypas** [comment]
Done. Tested it multiple times, killing power during the update. Rebooted into DFU mode every time and was rescued.

**Comment by peterantypas** [comment]
After multiple users in the field reported problems with the built-in STM32 bootloader and using STM32CubeProgrammer, it is now clear that this is not a good choice. MAIANA will need to have its own bootloader.

**Comment by peterantypas** [comment]
The bootloader does exist. I used it for my original test systems on my boat, so it has been exercised sufficiently. Time to dust it off!

**Comment by peterantypas** [comment]
Rescue mode verified on 2 different board revisions. Also, the LEDs are used to indicate DFU status which makes troubleshooting a whole lot easier.

**Comment by peterantypas** [comment]
The new bootloader has been released under FW 4.0.0 and OpenPlotter integration is complete as well. Closing.
