### ISSUE TITLE
wxPython based GUI utility for configuring and maintenance of the unit.

### ISSUE THREAD

**Issue by mgrouch** [peterantypas/maiana#91]
wxPython based GUI utility for configuring and maintenance of the Maiana AIS unit.
Forms can be easily designed using wxFormBuilder (included in bareboat necessities OS ver >= 2022-01-04)

There is something in openplotter which is not standalone and tightly coupled with OP.
(So it can't be used as-is by any generic unix distribution)

Thanks!

**Comment by peterantypas** [comment]
Yup, on the roadmap.

**Comment by sailoog** [comment]
Yes, openplotter-maiana app is not just a GUI to occasionally configuring and updating a MAIANA devices but a full integration with Signalk K and OpenPlotter notifications and IoT systems. You can even configure the device on the fly without taking control of the serial port for example enabling/disabling transmission.

But it would not be difficult to adapt this GUI to work standalone, you should just remove some dependencies, some daemons and you are done. It is pure wxPython, the GUI is quite simple so no need of wxFormBuilder. Let me know if you need help with this.

**Comment by peterantypas** [comment]
I’ve built wxPython apps before (including native executable packaging for Windows and Mac). 

But yeah, it might be easier to fork your code and strip stuff out. I’ll take a look.

**Comment by peterantypas** [comment]
I need to do this regardless for FW updates outside of OpenPlotter.

**Comment by peterantypas** [comment]
Version 0.1 of a standalone wxPython app is in https://github.com/peterantypas/maiana/tree/master/latest/Apps/maiana-update

No native executable packaging yet.

**Comment by mgrouch** [comment]
Nice! 
As a someone with plenty of experience designing UI forms, I have one small
comment:

Labels of input fields should be right aligned next to the input field.
Use flag wxALIGN_RIGHT
It's much easier to read 

(Most form designs I see are doing it wrong, by left aligning labels)

**Comment by mgrouch** [comment]
Does it need to be run as root or a user can be just a member of certain groups?
Which groups?

Thanks

**Comment by gah67** [comment]
As it is accessing a serial port it is usually wheel or dialout depending on the distribution
