### ISSUE TITLE
maiana setup with extisting VHF antenna

### ISSUE THREAD

**Issue by zjttoefs** [peterantypas/maiana#94]
If the boat already has a VHF antenna at the mast head, is it possible/sensible to use this instead of the bundled antenna?

Having two antennas up there would cause some interference, I would guess and it is extra wiring hassle.

**Comment by kagouraki** [comment]
You can use the vhf antenna on the mast.
You will need something similar to these ones.
https://www.milltechmarine.com/Antenna-Splitters_c_19.html

**Comment by zjttoefs** [comment]
Great! Thanks for the quick response.
